# Generated by Django 5.2.5 on 2025-08-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hoteluser_is_verified_hotelvendor_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelvendor',
            name='bussiness_name',
            field=models.CharField(blank=True, default='Hotel Vendor', max_length=100, null=True),
        ),
    ]
