# Generated by Django 5.2.5 on 2025-08-26 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_hotelvendor_bussiness_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelvendor',
            old_name='bussiness_name',
            new_name='business_name',
        ),
    ]
