# Generated by Django 5.2.5 on 2025-09-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_bussiness_name_hotelvendor_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_slug',
            field=models.SlugField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
