# Generated by Django 5.2.5 on 2025-09-06 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_hotel_hotel_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='offer_price',
            new_name='hotel_offer_price',
        ),
    ]
