# Generated by Django 5.2.5 on 2025-09-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_offer_price_hotel_hotel_offer_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='amenities',
        ),
        migrations.AddField(
            model_name='hotel',
            name='ameneties',
            field=models.ManyToManyField(blank=True, to='accounts.ameneties'),
        ),
    ]
